### PR TITLE
Feature social

### PR DESCRIPTION
**Pull request by AlejandroNo4**
This is the fifth Milestone for the "Social media website" project: It asks to create a model with associations for friendship between two users. I forgot to name the branch with an accurate name, but I'll take it in mind for the next one.

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑🛑**

Hello @AlejandroNo4 
This is a very good implementation of the project.
You made a good progress.
However let's make some changes

[REQUIRED]: Kindly add the invite button to the profile of users.
[REQUIRED: Add a feature to see friendship requests.
[REQUIRED]:  Add a feature to accept invitations of invitors and reject them.
[REQUIRED}: The timeline should include the user's own posts and posts of his/her friends.
[REQUIRED]: Kindly add a button to invite user to friendship on users list page and on single user page
[REQUIRED]: Kindly add unit and integration tests.

That's it
giphy (2)

Make the required changes and ask for another review👍👏
Happy coding💻💻

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨

## However, there are some changes required 👀 🧰 🔨 🔧

- I found a bug that prevented me from testing if the changes requested previously were implemented fully.
- I'll walk you through the bug so you can fix it before requesting a new code review:
1. I created a clean install of your project
2. I signed up as a new user "Oscar"
3. I created a post with the text "Hello"
4. I logged out.
5. When I tried to sign up as a new user "Carlos" to test your app, I got the following error screen:
image
- Please fix this before requesting a new code review.



### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Comment by AlejandroNo4** [comment]
Hello. 😊 The project has already been approved, but in the first two milestones, I got confused and had some errors that as I continued I forgot to fill out the complete project forms.😣

I remembered when I was filling out the last form, but it tells me that the milestone has not been approved. 

Captura de Pantalla 2021-04-19 a la(s) 19 53 11

One of the TSEs told me that I just need to fill out the project completion form. But this ☝🏽 is **not allowing me at all** to submit the form.
I don't really know what the correct steps are to follow. I am putting this pull request to fill the field of the form.

Thanks in advance.

**Review by umairarshadbutt — COMMENTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @AlejandroNo4 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##
## Important Note:
### You are working on **Milestone 5: Friendships v1**, and this project is not approved yet. In PR you attached an [image](https://user-images.githubusercontent.com/65735629/115475796-10c85500-a206-11eb-9b1e-5541954c51a0.png) for **Milestone 1**
### So please contact the student success team if your Milestone is approved on GitHub and there is an issue on the dashboard. And work on the **Milestone 5: Friendships v1** which you have submitted.
Kindly work on the suggested changes  👇.
- [x] Please work on suggested changes by the previous code reviewer.

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by AlejandroNo4** [comment]
Hello! I contacted Student Success and as they told me, I will explain in more detail what happened.

There was a lot of confusion on my part between milestones 5 and 6 (where I had to make some changes to the “friendships” model). When I finished the first version, I continued working. I created a new branch, but I made changes using migrations.

My mistake was that I did not wait for the revision. In order, it happened like this: 

- I pushed the changes that I was making. 
- 
- When I finished, I asked for the revision of milestone 6. 
- 
- Milestone 6 was approved, but milestone 5 required changes. 
- 
- The changes that I made in the new branch (from milestone 6), were reflected in the previous one (from milestone 5). Since the changes were big, it was impossible to even log in to the app from the “milestone 5” branch.

[here is the link that shows milestone 6 approval.](https://github.com/AlejandroNo4/ror-social-scaffold/pull/2)

And here is an image of my progress.

Captura de Pantalla 2021-04-28 a la(s) 21 19 24


I didn’t give it that much importance, and I thought that by default someone already approved it.

Well, my main problem (and mistake), is that I waited until I finished milestone 6 to submit the completion form for both milestones, but since milestone 5 has not been approved, the same form does not allow me to submit it. Also, I can’t go back and undo the already good code to code it wrongly.

Captura de Pantalla 2021-04-28 a la(s) 21 18 33

Thank you in advance.

**Review by voscarmv — COMMENTED** [review]
# Project status: Approved 💯 ✨ 😎 👍 

- Hi, I read your case and since you passed milestone 6 I think it's safe to assume that you've got all the concepts from the previous milestones mastered.
- I'm approving this submission on the dashboard to allow you to continue in the curriculum without trouble. Please let me know if you run into any additional trouble. I'm Oscar Mier on Slack.

### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
