### PR TITLE
Add ERD document and create docs folder

### PR DESCRIPTION
**Pull request by AlejandroNo4**
In this milestone, I created the ERD model to be the reference for the structure of the database.

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coder, 👋🏽 
**This is a great project you have going on**. 

- Well-done 💯 
    1. The ERD diagram is almost perfect.
    2. The linters are running just fine

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] I presume that the Action table is meant to be the likes table. If so, adding the type column in your table might be needless unless you are going to implement the various kinds of Action(likes).
All you need is the `user_id` for the user that reacted and the `post_id` for the post being reacted on. The third column should be the kind of Action such as the 👏🏽 , 👍🏽 , 👎🏽 , ❤️ , etc 
So if you are not going to implement this feature, I suggest you remove the type column in the Actions table. Else, you may proceed with this feature.

- [x] Visualize this as the User-Friendship relationship
```
    1. One Friendship  is sent by only One User.
    2. One User can send many Friendships.
    3. One Friendship is received by only One User.
    4. One User can receive many Friendships.
```
- Recall that a friendship should belong to the user and not the other way around, which is what is depicted in the ERD diagram.


### OPTIONAL

- [x] It is a better practice to use 'ID' as the PK, and not 'id'

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Comment by AlejandroNo4** [comment]
Hello! I made the changes, but for some reason, trying to delete the file ".DS_Store" was giving me a bunch of errors in the stylelint.

**Comment by AlejandroNo4** [comment]
Hello! I was trying to delete the file "DS_Store," but for some reason, it was giving me a bunch of errors with stylelint. Also, I accidentally closed the pull request, but I reopened it.

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- Your ERD is perfect :+1: 

To improve :factory_worker: [REQUIRED]:

- [x] Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [HINT] you can read this [article](https://code.likeagirl.io/how-to-get-rid-of-ds-store-and-node-modules-in-git-repositories-d37b8a391247?gi=515a0c7a0d13) which explains how to add the files to .gitignore_global which will prevent them from being added to any future project.

Nice to have :+1:  :

- [x] Please rename table `Action` to `Like` in order to make sure that your ERD will correspond with the DB that you are going to use.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by MahmoudBakr23 — APPROVED** [review]
# **Approved ✔✔**

<hr>

Good job working on the ERD and making the requested changes. You may now merge and submit. 👍 🥇 

Good luck with the next and happy coding 👨‍💻💻

**Pull request merged**
